export const EXERCISES = [
  // ── Chest ──
  { name: 'Bench Press (Barbell)',           category: 'Chest' },
  { name: 'Bench Press (Dumbbell)',          category: 'Chest' },
  { name: 'Bench Press (Smith Machine)',     category: 'Chest' },
  { name: 'Incline Bench Press (Barbell)',   category: 'Chest' },
  { name: 'Incline Bench Press (Dumbbell)',  category: 'Chest' },
  { name: 'Incline Bench Press (Smith Machine)', category: 'Chest' },
  { name: 'Decline Bench Press',             category: 'Chest' },
  { name: 'Decline Bench Press (Dumbbell)',  category: 'Chest' },
  { name: 'Incline Chest Press (Machine)',   category: 'Chest' },
  { name: 'Machine Chest Press',             category: 'Chest' },
  { name: 'Chest Fly (Dumbbell)',            category: 'Chest' },
  { name: 'Incline Chest Fly (Dumbbell)',    category: 'Chest' },
  { name: 'Chest Fly (Machine)',             category: 'Chest' },
  { name: 'Cable Fly',                       category: 'Chest' },
  { name: 'Low Cable Fly',                   category: 'Chest' },
  { name: 'High Cable Fly',                  category: 'Chest' },
  { name: 'Cable Crossover',                 category: 'Chest' },
  { name: 'Pec Deck',                        category: 'Chest' },
  { name: 'Push Up',                         category: 'Chest' },
  { name: 'Push Up (Weighted)',              category: 'Chest' },
  { name: 'Incline Push Up',                 category: 'Chest' },
  { name: 'Decline Push Up',                 category: 'Chest' },
  { name: 'Chest Dip',                       category: 'Chest' },
  { name: 'Landmine Press',                  category: 'Chest' },
  { name: 'Svend Press',                     category: 'Chest' },
  // ── Back ──
  { name: 'Deadlift (Barbell)',              category: 'Back' },
  { name: 'Deadlift (Dumbbell)',             category: 'Back' },
  { name: 'Deadlift (Trap Bar)',             category: 'Back' },
  { name: 'Romanian Deadlift',               category: 'Back' },
  { name: 'Sumo Deadlift',                   category: 'Back' },
  { name: 'Rack Pull',                       category: 'Back' },
  { name: 'Pull Up',                         category: 'Back' },
  { name: 'Pull Up (Weighted)',             category: 'Back' },
  { name: 'Chin Up',                         category: 'Back' },
  { name: 'Assisted Pull Up (Machine)',      category: 'Back' },
  { name: 'Lat Pulldown',                    category: 'Back' },
  { name: 'Lat Pulldown (Wide Grip)',        category: 'Back' },
  { name: 'Lat Pulldown (Close Grip)',       category: 'Back' },
  { name: 'Lat Pulldown (Neutral Grip)',     category: 'Back' },
  { name: 'Single Arm Lat Pulldown (Cable)', category: 'Back' },
  { name: 'Straight Arm Pulldown',           category: 'Back' },
  { name: 'Seated Cable Row',                category: 'Back' },
  { name: 'Cable Row (Wide Grip)',           category: 'Back' },
  { name: 'Bent Over Row (Barbell)',         category: 'Back' },
  { name: 'Bent Over Row (Dumbbell)',        category: 'Back' },
  { name: 'Pendlay Row',                     category: 'Back' },
  { name: 'T-Bar Row',                       category: 'Back' },
  { name: 'Chest Supported Row (Machine)',   category: 'Back' },
  { name: 'Chest Supported Row (Dumbbell)',  category: 'Back' },
  { name: 'Seated Row (Machine)',            category: 'Back' },
  { name: 'Single Arm Dumbbell Row',         category: 'Back' },
  { name: 'Meadows Row',                     category: 'Back' },
  { name: 'Inverted Row',                    category: 'Back' },
  { name: 'Face Pull',                       category: 'Back' },
  { name: 'Shrug (Barbell)',                 category: 'Back' },
  { name: 'Shrug (Dumbbell)',                category: 'Back' },
  { name: 'Shrug (Machine)',                 category: 'Back' },
  { name: 'Shrug (Cable)',                   category: 'Back' },
  // ── Shoulders ──
  { name: 'Overhead Press (Barbell)',        category: 'Shoulders' },
  { name: 'Overhead Press (Dumbbell)',       category: 'Shoulders' },
  { name: 'Overhead Press (Smith Machine)',  category: 'Shoulders' },
  { name: 'Seated Dumbbell Press',           category: 'Shoulders' },
  { name: 'Machine Shoulder Press',          category: 'Shoulders' },
  { name: 'Arnold Press',                    category: 'Shoulders' },
  { name: 'Push Press',                      category: 'Shoulders' },
  { name: 'Lateral Raise (Dumbbell)',        category: 'Shoulders' },
  { name: 'Lateral Raise (Cable)',           category: 'Shoulders' },
  { name: 'Lateral Raise (Machine)',         category: 'Shoulders' },
  { name: 'Lean-In Lateral Raise (Cable)',   category: 'Shoulders' },
  { name: 'Front Raise (Dumbbell)',          category: 'Shoulders' },
  { name: 'Front Raise (Cable)',             category: 'Shoulders' },
  { name: 'Front Raise (Plate)',             category: 'Shoulders' },
  { name: 'Rear Delt Fly (Dumbbell)',        category: 'Shoulders' },
  { name: 'Rear Delt Fly (Cable)',           category: 'Shoulders' },
  { name: 'Rear Delt Fly (Machine)',         category: 'Shoulders' },
  { name: 'Reverse Pec Deck',                category: 'Shoulders' },
  { name: 'Upright Row',                     category: 'Shoulders' },
  { name: 'Upright Row (Cable)',             category: 'Shoulders' },
  { name: 'Cuban Press',                     category: 'Shoulders' },
  { name: 'Landmine Shoulder Press',         category: 'Shoulders' },
  // ── Biceps ──
  { name: 'Barbell Curl',                    category: 'Biceps' },
  { name: 'EZ Bar Curl',                     category: 'Biceps' },
  { name: 'Dumbbell Curl',                   category: 'Biceps' },
  { name: 'Hammer Curl',                     category: 'Biceps' },
  { name: 'Hammer Curl (Cable)',             category: 'Biceps' },
  { name: 'Incline Dumbbell Curl',           category: 'Biceps' },
  { name: 'Cable Curl',                      category: 'Biceps' },
  { name: 'Bayesian Curl (Cable)',           category: 'Biceps' },
  { name: 'Preacher Curl',                   category: 'Biceps' },
  { name: 'Preacher Curl (Machine)',         category: 'Biceps' },
  { name: 'Preacher Curl (Dumbbell)',        category: 'Biceps' },
  { name: 'Concentration Curl',              category: 'Biceps' },
  { name: 'Spider Curl',                     category: 'Biceps' },
  { name: 'Reverse Curl',                    category: 'Biceps' },
  { name: 'Reverse Curl (Cable)',            category: 'Biceps' },
  { name: 'Bicep Curl (Machine)',            category: 'Biceps' },
  // ── Triceps ──
  { name: 'Tricep Pushdown (Cable)',         category: 'Triceps' },
  { name: 'Tricep Pushdown (Rope)',          category: 'Triceps' },
  { name: 'Tricep Pushdown (V-Bar)',         category: 'Triceps' },
  { name: 'Overhead Tricep Extension',       category: 'Triceps' },
  { name: 'Overhead Tricep Extension (Cable)', category: 'Triceps' },
  { name: 'Overhead Tricep Extension (Dumbbell)', category: 'Triceps' },
  { name: 'Skull Crusher',                   category: 'Triceps' },
  { name: 'Skull Crusher (EZ Bar)',          category: 'Triceps' },
  { name: 'Close Grip Bench Press',          category: 'Triceps' },
  { name: 'Tricep Dip',                      category: 'Triceps' },
  { name: 'Tricep Dip (Machine)',            category: 'Triceps' },
  { name: 'Bench Dip',                       category: 'Triceps' },
  { name: 'Diamond Push Up',                 category: 'Triceps' },
  { name: 'Tricep Kickback',                 category: 'Triceps' },
  { name: 'Tricep Kickback (Cable)',         category: 'Triceps' },
  { name: 'Tricep Extension (Machine)',      category: 'Triceps' },
  { name: 'JM Press',                        category: 'Triceps' },
  // ── Quads ──
  { name: 'Squat (Barbell)',                 category: 'Quads' },
  { name: 'Squat (Smith Machine)',           category: 'Quads' },
  { name: 'Front Squat',                     category: 'Quads' },
  { name: 'Goblet Squat',                    category: 'Quads' },
  { name: 'Hack Squat',                      category: 'Quads' },
  { name: 'Pendulum Squat',                  category: 'Quads' },
  { name: 'Leg Press',                       category: 'Quads' },
  { name: 'Leg Press (Single Leg)',          category: 'Quads' },
  { name: 'Leg Extension',                   category: 'Quads' },
  { name: 'Leg Extension (Single Leg)',      category: 'Quads' },
  { name: 'Bulgarian Split Squat',           category: 'Quads' },
  { name: 'Bulgarian Split Squat (Dumbbell)', category: 'Quads' },
  { name: 'Lunge (Barbell)',                 category: 'Quads' },
  { name: 'Lunge (Dumbbell)',                category: 'Quads' },
  { name: 'Walking Lunge',                   category: 'Quads' },
  { name: 'Sissy Squat',                     category: 'Quads' },
  { name: 'Box Squat',                       category: 'Quads' },
  // ── Hamstrings ──
  { name: 'Leg Curl (Lying)',                category: 'Hamstrings' },
  { name: 'Leg Curl (Seated)',               category: 'Hamstrings' },
  { name: 'Leg Curl (Standing)',             category: 'Hamstrings' },
  { name: 'Nordic Hamstring Curl',           category: 'Hamstrings' },
  { name: 'Romanian Deadlift (Dumbbell)',    category: 'Hamstrings' },
  { name: 'Romanian Deadlift (Smith Machine)', category: 'Hamstrings' },
  { name: 'Stiff Leg Deadlift',              category: 'Hamstrings' },
  { name: 'Good Morning',                    category: 'Hamstrings' },
  { name: 'Glute Ham Raise',                 category: 'Hamstrings' },
  { name: 'Cable Pull Through',              category: 'Hamstrings' },
  // ── Glutes ──
  { name: 'Hip Thrust (Barbell)',            category: 'Glutes' },
  { name: 'Hip Thrust (Machine)',            category: 'Glutes' },
  { name: 'Hip Thrust (Smith Machine)',      category: 'Glutes' },
  { name: 'Hip Thrust (Bodyweight)',         category: 'Glutes' },
  { name: 'Glute Bridge',                    category: 'Glutes' },
  { name: 'Cable Kickback',                  category: 'Glutes' },
  { name: 'Glute Kickback (Machine)',        category: 'Glutes' },
  { name: 'Sumo Squat',                      category: 'Glutes' },
  { name: 'Step Up',                         category: 'Glutes' },
  { name: 'Hip Abduction (Cable)',           category: 'Glutes' },
  { name: 'Abductor Machine',               category: 'Glutes' },
  { name: 'Hip Adduction (Machine)',         category: 'Glutes' },
  { name: 'Donkey Kick',                     category: 'Glutes' },
  // ── Calves ──
  { name: 'Calf Raise (Standing Machine)',   category: 'Calves' },
  { name: 'Calf Raise (Seated Machine)',     category: 'Calves' },
  { name: 'Calf Raise (Smith Machine)',      category: 'Calves' },
  { name: 'Calf Raise (Barbell)',            category: 'Calves' },
  { name: 'Calf Raise (Dumbbell)',           category: 'Calves' },
  { name: 'Calf Raise (Leg Press)',          category: 'Calves' },
  { name: 'Calf Press (Machine)',            category: 'Calves' },
  { name: 'Jump Rope',                       category: 'Calves' },
  // ── Core ──
  { name: 'Plank',                           category: 'Core' },
  { name: 'Side Plank',                      category: 'Core' },
  { name: 'Crunch',                          category: 'Core', logType: 'bodyweight' },
  { name: 'Cable Crunch',                    category: 'Core' },
  { name: 'Crunch (Machine)',                category: 'Core' },
  { name: 'Leg Raise (Hanging)',             category: 'Core', logType: 'bodyweight' },
  { name: 'Leg Raise (Lying)',               category: 'Core' },
  { name: "Leg Raise (Captain's Chair)", category: 'Core' },
  { name: 'Russian Twist',                   category: 'Core' },
  { name: 'Ab Wheel Rollout',               category: 'Core' },
  { name: 'Decline Sit Up',                 category: 'Core' },
  { name: 'Sit Up',                          category: 'Core' },
  { name: 'Mountain Climber',                category: 'Core' },
  { name: 'Bicycle Crunch',                  category: 'Core' },
  { name: 'Dragon Flag',                     category: 'Core' },
  { name: 'Pallof Press',                    category: 'Core' },
  { name: 'Woodchopper (Cable)',             category: 'Core' },
  { name: 'Hollow Hold',                     category: 'Core' },
  // ── Cardio ──
  { name: 'Running (Treadmill)',             category: 'Cardio' },
  { name: 'Running (Outdoor)',               category: 'Cardio' },
  { name: 'Incline Walk (Treadmill)',        category: 'Cardio' },
  { name: 'Cycling (Stationary)',            category: 'Cardio' },
  { name: 'Cycling (Outdoor)',               category: 'Cardio' },
  { name: 'Rowing Machine',                  category: 'Cardio' },
  { name: 'Stair Master',                    category: 'Cardio' },
  { name: 'Assault Bike',                    category: 'Cardio' },
  { name: 'Ski Erg',                         category: 'Cardio' },
  { name: 'Elliptical',                      category: 'Cardio' },
  { name: 'Swimming',                        category: 'Cardio' },
  // ── Kettlebell (ballistic / grind — Rogan-style strength & conditioning) ──
  // All loaded (weight × reps) unless noted. Full-body moves are filed under
  // their primary driver so weekly set-counting stays meaningful.
  { name: 'Kettlebell Swing',                category: 'Hamstrings' },
  { name: 'Kettlebell Swing (American)',     category: 'Shoulders' },
  { name: 'Kettlebell Deadlift',             category: 'Hamstrings' },
  { name: 'Kettlebell Romanian Deadlift',    category: 'Hamstrings' },
  { name: 'Kettlebell Goblet Squat',         category: 'Quads' },
  { name: 'Kettlebell Front Squat',          category: 'Quads' },
  { name: 'Kettlebell Lunge',                category: 'Quads' },
  { name: 'Kettlebell Clean',                category: 'Shoulders' },
  { name: 'Kettlebell Clean and Press',      category: 'Shoulders' },
  { name: 'Kettlebell Clean and Jerk',       category: 'Shoulders' },
  { name: 'Kettlebell Push Press',           category: 'Shoulders' },
  { name: 'Kettlebell Press (Overhead)',     category: 'Shoulders' },
  { name: 'Kettlebell Bottoms-Up Press',     category: 'Shoulders' },
  { name: 'Kettlebell Snatch',               category: 'Shoulders' },
  { name: 'Kettlebell High Pull',            category: 'Shoulders' },
  { name: 'Kettlebell Sumo Deadlift High Pull', category: 'Shoulders' },
  { name: 'Kettlebell Thruster',             category: 'Quads' },
  { name: 'Kettlebell Row',                  category: 'Back' },
  { name: 'Kettlebell Renegade Row',         category: 'Back' },
  { name: 'Kettlebell Halo',                 category: 'Shoulders' },
  { name: 'Kettlebell Windmill',             category: 'Core' },
  { name: 'Kettlebell Figure 8',             category: 'Core' },
  { name: 'Kettlebell Around the World',     category: 'Core' },
  { name: 'Kettlebell Turkish Get-Up',       category: 'Core' },
  { name: 'Kettlebell Overhead Carry',       category: 'Shoulders', logType: 'duration' },
  { name: 'Kettlebell Farmer Carry',         category: 'Back',       logType: 'duration' },
  { name: 'Kettlebell Suitcase Carry',       category: 'Core',       logType: 'duration' },
  // ── Conditioning / circuit / metcon ──
  { name: 'Burpee',                          category: 'Core',    logType: 'bodyweight' },
  { name: 'Devil Press',                     category: 'Shoulders' },
  { name: 'Box Jump',                        category: 'Quads',   logType: 'bodyweight' },
  { name: 'Jump Squat',                      category: 'Quads',   logType: 'bodyweight' },
  { name: 'Jumping Lunge',                   category: 'Quads',   logType: 'bodyweight' },
  { name: 'Wall Ball',                       category: 'Quads' },
  { name: 'Medicine Ball Slam',              category: 'Core' },
  { name: 'Medicine Ball Chest Pass',        category: 'Chest' },
  { name: 'Battle Ropes',                    category: 'Cardio',  logType: 'duration' },
  { name: 'Sled Push',                       category: 'Quads' },
  { name: 'Sled Pull',                       category: 'Back' },
  { name: 'Tire Flip',                       category: 'Back' },
  { name: 'Sledgehammer Swing',              category: 'Core',    logType: 'bodyweight' },
  { name: 'Bear Crawl',                      category: 'Core',    logType: 'duration' },
  { name: 'Jumping Jacks',                   category: 'Cardio',  logType: 'duration' },
  { name: 'High Knees',                      category: 'Cardio',  logType: 'duration' },
];

export const CATEGORIES = [...new Set(EXERCISES.map(e => e.category))];

export const CATEGORY_COLORS = {
  Chest: '#f43f5e', Back: '#38bdf8', Shoulders: '#fbbf24',
  Biceps: '#34d399', Triceps: '#a78bfa', Quads: '#f97316',
  Hamstrings: '#f472b6', Glutes: '#e879f9', Calves: '#2dd4bf',
  Core: '#facc15', Cardio: '#60a5fa',
};

// ── Multi-muscle attribution for compound lifts ──────────────────────────────
// A single `category` per exercise is accurate for isolation work but understates
// true stimulus for compounds: a back squat is filed under Quads but loads the
// glutes hard at end-range hip extension; an RDL is filed under Hamstrings but is
// a primary glute hinge. Weekly set-counting that reads `category` alone therefore
// flags glutes/hamstrings as "under-trained" when they are in fact being loaded
// indirectly — and can't tell that apart from a real gap with zero carryover
// (e.g. calves — no compound loads ankle ROM meaningfully).
//
// SECONDARY_MUSCLES maps an exercise name to the muscle groups it loads BEYOND its
// primary `category`, each as a fractional "effective set" weight: 0.5 means one
// working set of this lift counts as half a set of stimulus for that muscle. The
// primary category is always an implicit 1.0 and is never repeated here. Values are
// deliberately conservative — they reflect the muscle's mechanical role in the lift,
// not a promise of equal hypertrophy. Only the muscle groups the app already tracks
// (see CATEGORIES) are used; finer distinctions (adductors, spinal erectors…) are not.
//
// Pure isolation lifts (leg extension, leg curl, curls, raises, calf work…) have NO
// entry on purpose: they load one muscle, so a genuine gap there stays visible as a
// true gap rather than being papered over by phantom indirect volume.
export const SECONDARY_MUSCLES = {
  // ── Chest presses → triceps + front-delt (Shoulders) ──
  'Bench Press (Barbell)':          { Triceps: 0.35, Shoulders: 0.25 },
  'Bench Press (Dumbbell)':         { Triceps: 0.3,  Shoulders: 0.25 },
  'Bench Press (Smith Machine)':    { Triceps: 0.35, Shoulders: 0.25 },
  'Incline Bench Press (Barbell)':  { Shoulders: 0.35, Triceps: 0.3 },
  'Incline Bench Press (Dumbbell)': { Shoulders: 0.35, Triceps: 0.25 },
  'Incline Bench Press (Smith Machine)': { Shoulders: 0.35, Triceps: 0.3 },
  'Decline Bench Press':            { Triceps: 0.35 },
  'Decline Bench Press (Dumbbell)': { Triceps: 0.3 },
  'Incline Chest Press (Machine)':  { Shoulders: 0.3, Triceps: 0.25 },
  'Machine Chest Press':            { Triceps: 0.3, Shoulders: 0.2 },
  'Push Up':                        { Triceps: 0.3, Shoulders: 0.2 },
  'Push Up (Weighted)':             { Triceps: 0.3, Shoulders: 0.2 },
  'Incline Push Up':                { Triceps: 0.3, Shoulders: 0.2 },
  'Decline Push Up':                { Shoulders: 0.3, Triceps: 0.25 },
  'Chest Dip':                      { Triceps: 0.4 },
  'Landmine Press':                 { Shoulders: 0.4, Triceps: 0.2 },
  // ── Deadlifts / pulls filed under Back → posterior chain ──
  'Deadlift (Barbell)':             { Glutes: 0.5, Hamstrings: 0.5 },
  'Deadlift (Dumbbell)':            { Glutes: 0.5, Hamstrings: 0.5 },
  'Deadlift (Trap Bar)':            { Quads: 0.5, Glutes: 0.5, Hamstrings: 0.35 },
  'Romanian Deadlift':              { Hamstrings: 0.8, Glutes: 0.6 },
  'Sumo Deadlift':                  { Glutes: 0.6, Hamstrings: 0.4, Quads: 0.4 },
  'Rack Pull':                      { Glutes: 0.4, Hamstrings: 0.35 },
  // ── Vertical / horizontal pulls → biceps ──
  'Pull Up':                        { Biceps: 0.35 },
  'Pull Up (Weighted)':             { Biceps: 0.35 },
  'Chin Up':                        { Biceps: 0.5 },
  'Assisted Pull Up (Machine)':     { Biceps: 0.35 },
  'Lat Pulldown':                   { Biceps: 0.35 },
  'Lat Pulldown (Wide Grip)':       { Biceps: 0.3 },
  'Lat Pulldown (Close Grip)':      { Biceps: 0.4 },
  'Lat Pulldown (Neutral Grip)':    { Biceps: 0.4 },
  'Single Arm Lat Pulldown (Cable)':{ Biceps: 0.35 },
  'Seated Cable Row':               { Biceps: 0.35 },
  'Cable Row (Wide Grip)':          { Biceps: 0.3 },
  'Bent Over Row (Barbell)':        { Biceps: 0.35 },
  'Bent Over Row (Dumbbell)':       { Biceps: 0.35 },
  'Pendlay Row':                    { Biceps: 0.35 },
  'T-Bar Row':                      { Biceps: 0.35 },
  'Chest Supported Row (Machine)':  { Biceps: 0.35 },
  'Chest Supported Row (Dumbbell)': { Biceps: 0.35 },
  'Seated Row (Machine)':           { Biceps: 0.35 },
  'Single Arm Dumbbell Row':        { Biceps: 0.35 },
  'Meadows Row':                    { Biceps: 0.35 },
  'Inverted Row':                   { Biceps: 0.35 },
  'Kettlebell Row':                 { Biceps: 0.35 },
  'Kettlebell Renegade Row':        { Biceps: 0.3, Core: 0.3 },
  'Face Pull':                      { Shoulders: 0.4 },
  // ── Overhead presses → triceps ──
  'Overhead Press (Barbell)':       { Triceps: 0.35 },
  'Overhead Press (Dumbbell)':      { Triceps: 0.3 },
  'Overhead Press (Smith Machine)': { Triceps: 0.35 },
  'Seated Dumbbell Press':          { Triceps: 0.3 },
  'Machine Shoulder Press':         { Triceps: 0.3 },
  'Arnold Press':                   { Triceps: 0.3 },
  'Push Press':                     { Triceps: 0.35 },
  'Landmine Shoulder Press':        { Triceps: 0.3 },
  // ── Triceps compounds → chest / front-delt ──
  'Close Grip Bench Press':         { Chest: 0.5, Shoulders: 0.2 },
  'Tricep Dip':                     { Chest: 0.3, Shoulders: 0.2 },
  'Tricep Dip (Machine)':           { Chest: 0.25 },
  'Bench Dip':                      { Chest: 0.2 },
  'Diamond Push Up':                { Chest: 0.4, Shoulders: 0.2 },
  'JM Press':                       { Chest: 0.3 },
  // ── Squat pattern (Quads) → glutes (+ hamstrings on the deepest) ──
  'Squat (Barbell)':                { Glutes: 0.5, Hamstrings: 0.25 },
  'Squat (Smith Machine)':          { Glutes: 0.45 },
  'Front Squat':                    { Glutes: 0.4 },
  'Goblet Squat':                   { Glutes: 0.4 },
  'Hack Squat':                     { Glutes: 0.35 },
  'Pendulum Squat':                 { Glutes: 0.4 },
  'Leg Press':                      { Glutes: 0.4 },
  'Leg Press (Single Leg)':         { Glutes: 0.45 },
  'Bulgarian Split Squat':          { Glutes: 0.5 },
  'Bulgarian Split Squat (Dumbbell)': { Glutes: 0.5 },
  'Lunge (Barbell)':                { Glutes: 0.5 },
  'Lunge (Dumbbell)':               { Glutes: 0.5 },
  'Walking Lunge':                  { Glutes: 0.5 },
  'Box Squat':                      { Glutes: 0.5, Hamstrings: 0.3 },
  'Kettlebell Goblet Squat':        { Glutes: 0.4 },
  'Kettlebell Front Squat':         { Glutes: 0.4 },
  'Kettlebell Lunge':               { Glutes: 0.5 },
  'Kettlebell Thruster':            { Shoulders: 0.4, Glutes: 0.3, Triceps: 0.2 },
  'Wall Ball':                      { Glutes: 0.35, Shoulders: 0.3 },
  'Sled Push':                      { Glutes: 0.4, Hamstrings: 0.3, Calves: 0.3 },
  // ── Hip hinge (Hamstrings) → glutes ──
  'Romanian Deadlift (Dumbbell)':   { Glutes: 0.5 },
  'Romanian Deadlift (Smith Machine)': { Glutes: 0.5 },
  'Stiff Leg Deadlift':             { Glutes: 0.5 },
  'Good Morning':                   { Glutes: 0.5 },
  'Glute Ham Raise':                { Glutes: 0.4 },
  'Cable Pull Through':             { Glutes: 0.6 },
  'Kettlebell Swing':               { Glutes: 0.6 },
  'Kettlebell Deadlift':            { Glutes: 0.5 },
  'Kettlebell Romanian Deadlift':   { Glutes: 0.5 },
  // ── Glute-primary compounds → hamstrings / quads ──
  'Hip Thrust (Barbell)':           { Hamstrings: 0.35 },
  'Hip Thrust (Machine)':           { Hamstrings: 0.3 },
  'Hip Thrust (Smith Machine)':     { Hamstrings: 0.35 },
  'Hip Thrust (Bodyweight)':        { Hamstrings: 0.3 },
  'Glute Bridge':                   { Hamstrings: 0.35 },
  'Sumo Squat':                     { Quads: 0.5, Hamstrings: 0.25 },
  'Step Up':                        { Quads: 0.5, Hamstrings: 0.2 },
};

// Expand an exercise-like object ({ name, category }) into its muscle
// contributions: the primary category at 1.0, plus any secondary fractions from
// SECONDARY_MUSCLES. `primary: true` marks the direct-volume entry so callers can
// separate direct stimulus (drawn solid on the balance chart) from indirect
// carryover (drawn as a lighter band) — the distinction that lets a real gap read
// differently from a muscle that's quietly being trained by compounds.
export function muscleContributions(ex) {
  const primary = (ex && ex.category) || 'Other';
  const out = [{ muscle: primary, frac: 1, primary: true }];
  const sec = ex && SECONDARY_MUSCLES[ex.name];
  if (sec) for (const [muscle, frac] of Object.entries(sec)) {
    if (muscle !== primary) out.push({ muscle, frac, primary: false });
  }
  return out;
}
